In [1]:
import pandas as pd

In [2]:
titanic= pd.read_csv('titanic_raw.csv')

In [3]:
pd.options.display.max_rows

60

In [4]:
pd.options.display.min_rows

10

In [5]:
pd.options.display.max_columns

20

In [6]:
pd.options.display.max_rows = 900

In [7]:
titanic

,,,,,This,is,the,Titanic,Dataset.
It,contains,all,passengers,that,were,aboard,the,titanic,when
the,tragic,disaster,occured,in,the,year,19,1,2
0,0,3,male,22.0,1,0,$7.25,S,NaN
1,1,1,female,38.0,1,0,$71.2833,C,C
2,1,3,female,26.0,0,0,$7.925,S,NaN
3,1,1,female,35.0,1,0,$53.1,S,C
4,0,3,male,35.0,0,0,$8.05,S,NaN
5,0,3,male,Missing Data,0,0,$8.4583,Q,NaN
6,0,1,male,54.0,0,0,$51.8625,S,E
7,0,3,male,2.0,3,1,$21.075,S,NaN
8,1,3,female,27.0,0,2,$11.1333,S,NaN
9,1,2,female,14.0,1,0,$30.0708,C,NaN
10,1,3,female,4.0,1,1,$16.7,S,G
11,1,1,female,58.0,0,0,$26.55,S,C
12,0,3,male,20.0,0,0,$8.05,S,NaN
13,0,3,male,39.0,1,5,$31.275,S,NaN
14,0,3,female,14.0,0,0,$7.8542,S,NaN
15,1,2,female,55.0,0,0,$16.0,S,NaN
16,0,3,male,2.0,4,1,$29.125,Q,NaN
17,1,2,male,Missing Data,0,0,$13.0,S,NaN
18,0,3,female,31.0,1,0,$18.0,S,NaN
19,1,3,female,Missing Data,0,0,$7.225,C,NaN
20,0,2,male,35.0,0,0,$26.0,S,NaN
21,1,2,male,34.0,0,0,$13.0,S,D
22,1,3,female,15.0,0,0,$8.0292,Q,NaN
23,1,1,male,28.0,0,0,$35.5,S,A
24,0,3,female,8.0,3,1,$21.075,S,NaN
25,1,3,female,38.0,1,5,$31.3875,S,NaN
26,0,3,male,Missing Data,0,0,$7.225,C,NaN
27,0,1,male,19.0,3,2,$263.0,S,C
28,1,3,female,Missing Data,0,0,$7.8792,Q,NaN
29,0,3,male,Missing Data,0,0,$7.8958,S,NaN
30,0,1,male,40.0,0,0,$27.7208,C,NaN
31,1,1,female,Missing Data,1,0,$146.5208,C,B
32,1,3,female,Missing Data,0,0,$7.75,Q,NaN
33,0,2,male,66.0,0,0,$10.5,S,NaN
34,0,1,male,28.0,1,0,$82.1708,C,NaN
35,0,1,male,42.0,1,0,$52.0,S,NaN
36,1,3,male,Missing Data,0,0,$7.2292,C,NaN
37,0,3,male,21.0,0,0,$8.05,S,NaN
38,0,3,female,18.0,2,0,$18.0,S,NaN
39,1,3,female,14.0,1,0,$11.2417,C,NaN
40,0,3,female,40.0,1,0,$9.475,S,NaN
41,0,2,female,27.0,1,0,$21.0,S,NaN
42,0,3,male,Missing Data,0,0,$7.8958,C,NaN
43,1,2,female,3.0,1,2,$41.5792,C,NaN
44,1,3,female,19.0,0,0,$7.8792,Q,NaN
45,0,3,male,Missing Data,0,0,$8.05,S,NaN
46,0,3,male,Missing Data,1,0,$15.5,Q,NaN
47,1,3,female,Missing Data,0,0,$7.75,Q,NaN
48,0,3,male,Missing Data,2,0,$21.6792,C,NaN
49,0,3,female,18.0,1,0,$17.8,S,NaN
50,0,3,male,7.0,4,1,$39.6875,S,NaN
51,0,3,male,21.0,0,0,$7.8,S,NaN
52,1,1,female,49.0,1,0,$76.7292,C,D
53,1,2,female,29.0,1,0,$26.0,S,NaN
54,0,1,male,65.0,0,1,$61.9792,C,B
55,1,1,male,Missing Data,0,0,$35.5,S,C
56,1,2,female,21.0,0,0,$10.5,S,NaN
57,0,3,male,28.5,0,0,$7.2292,C,NaN
58,1,2,female,5.0,1,2,$27.75,S,NaN
59,0,3,male,11.0,5,2,$46.9,S,NaN
60,0,3,male,22.0,0,0,$7.2292,C,NaN
61,1,1,female,38.0,0,0,$80.0,NaN,B
62,0,1,male,45.0,1,0,$83.475,S,C
63,0,3,male,4.0,3,2,$27.9,S,NaN
64,0,1,male,Missing Data,0,0,$27.7208,C,NaN
65,1,3,male,Missing Data,1,1,$15.2458,C,NaN
66,1,2,female,29.0,0,0,$10.5,S,F
67,0,3,male,19.0,0,0,$8.1583,S,NaN
68,1,3,female,17.0,4,2,$7.925,S,NaN
69,0,3,male,26.0,2,0,$8.6625,S,NaN
70,0,2,male,32.0,0,0,$10.5,S,NaN
71,0,3,female,16.0,5,2,$46.9,S,NaN
72,0,2,male,21.0,0,0,$73.5,S,NaN
73,0,3,male,26.0,1,0,$14.4542,C,NaN
74,1,3,male,32.0,0,0,$56.4958,S,NaN
75,0,3,male,25.0,0,0,$7.65,S,F
76,0,3,male,Missing Data,0,0,$7.8958,S,NaN
77,0,3,male,Missing Data,0,0,$8.05,S,NaN
78,1,2,male,0.83,0,2,$29.0,S,NaN
79,1,3,female,30.0,0,0,$12.475,S,NaN
80,0,3,male,22.0,0,0,$9.0,S,NaN
81,1,3,male,29.0,0,0,$9.5,S,NaN
82,1,3,female,Missing Data,0,0,$7.7875,Q,NaN
83,0,1,male,28.0,0,0,$47.1,S,NaN
84,1,2,female,17.0,0,0,$10.5,S,NaN
85,1,3,female,33.0,3,0,$15.85,S,NaN
86,0,3,male,16.0,1,3,$34.375,S,NaN
87,0,3,male,Missing Data,0,0,$8.05,S,NaN
88,1,1,female,23.0,3,2,$263.0,S,C
89,0,3,male,24.0,0,0,$8.05,S,NaN
90,0,3,male,29.0,0,0,$8.05,S,NaN
91,0,3,male,20.0,0,0,$7.8542,S,NaN
92,0,1,male,46.0,1,0,$61.175,S,E
93,0,3,male,26.0,1,2,$20.575,S,NaN
94,0,3,male,59.0,0,0,$7.25,S,NaN
95,0,3,male,Missing Data,0,0,$8.05,S,NaN
96,0,1,male,71.0,0,0,$34.6542,C,A
97,1,1,male,23.0,0,1,$63.3583,C,D
98,1,2,female,34.0,0,1,$23.0,S,NaN
99,0,2,male,34.0,1,0,$26.0,S,NaN
100,0,3,female,28.0,0,0,$7.8958,S,NaN
101,0,3,male,Missing Data,0,0,$7.8958,S,NaN
102,0,1,male,21.0,0,1,$77.2875,S,D
103,0,3,male,33.0,0,0,$8.6542,S,NaN
104,0,3,male,37.0,2,0,$7.925,S,NaN
105,0,3,male,28.0,0,0,$7.8958,S,NaN
106,1,3,female,21.0,0,0,$7.65,S,NaN
107,1,3,male,Missing Data,0,0,$7.775,S,NaN
108,0,3,male,38.0,0,0,$7.8958,S,NaN
109,1,3,female,Missing Data,1,0,$24.15,Q,NaN
110,0,1,male,47.0,0,0,$52.0,S,C
111,0,3,female,14.5,1,0,$14.4542,C,NaN
112,0,3,male,22.0,0,0,$8.05,S,NaN
113,0,3,female,20.0,1,0,$9.825,S,NaN
114,0,3,female,17.0,0,0,$14.4583,C,NaN
115,0,3,male,21.0,0,0,$7.925,S,NaN
116,0,3,male,70.5,0,0,$7.75,Q,NaN
117,0,2,male,29.0,1,0,$21.0,S,NaN
118,0,1,male,24.0,0,1,$247.5208,C,B
119,0,3,female,2.0,4,2,$31.275,S,NaN
120,0,2,male,21.0,2,0,$73.5,S,NaN
121,0,3,male,Missing Data,0,0,$8.05,S,NaN
122,0,2,male,32.5,1,0,$30.0708,C,NaN
123,yes,2,female,32.5,0,0,$13.0,S,E
124,0,1,male,54.0,0,1,$77.2875,S,D
125,1,3,male,12.0,1,0,$11.2417,C,NaN
126,0,3,male,Missing Data,0,0,$7.75,Q,NaN
127,1,3,male,24.0,0,0,$7.1417,S,NaN
128,1,3,female,Missing Data,1,1,$22.3583,C,F
129,0,3,male,45.0,0,0,$6.975,S,NaN
130,0,3,male,33.0,0,0,$7.8958,C,NaN
131,0,3,male,20.0,0,0,$7.05,S,NaN
132,0,3,female,47.0,1,0,$14.5,S,NaN
133,1,2,female,29.0,1,0,$26.0,S,NaN
134,0,2,male,25.0,0,0,$13.0,S,NaN
135,0,2,male,23.0,0,0,$15.0458,C,NaN
136,1,1,female,19.0,0,2,$26.2833,S,D
137,0,1,male,37.0,1,0,$53.1,S,C
138,0,3,male,16.0,0,0,$9.2167,S,NaN
139,0,1,male,24.0,0,0,$79.2,C,B
140,0,3,female,Missing Data,0,2,$15.2458,C,NaN
141,1,3,female,22.0,0,0,$7.75,S,NaN
142,1,3,female,24.0,1,0,$15.85,S,NaN
143,0,3,male,19.0,0,0,$6.75,Q,NaN
144,0,2,male,18.0,0,0,$11.5,S,NaN
145,0,2,male,19.0,1,1,$36.75,S,NaN
146,1,3,male,27.0,0,0,$7.7958,S,NaN
147,0,3,female,9.0,2,2,$34.375,S,NaN
148,0,2,male,36.5,0,2,$26.0,S,F
149,0,2,male,42.0,0,0,$13.0,S,NaN
150,0,2,male,51.0,0,0,$12.525,S,NaN
151,1,1,female,22.0,1,0,$66.6,S,C
152,0,3,male,55.5,0,0,$8.05,S,NaN
153,0,3,male,40.5,0,2,$14.5,S,NaN
154,0,3,male,Missing Data,0,0,$7.3125,S,NaN
155,0,1,male,51.0,0,1,$61.3792,C,NaN
156,1,3,female,16.0,0,0,$7.7333,Q,NaN
157,0,3,male,30.0,0,0,$8.05,S,NaN
158,0,3,male,Missing Data,0,0,$8.6625,S,NaN
159,0,3,male,Missing Data,8,2,$69.55,S,NaN
160,0,3,male,44.0,0,1,$16.1,S,NaN
161,1,2,female,40.0,0,0,$15.75,S,NaN
162,0,3,male,26.0,0,0,$7.775,S,NaN
163,0,3,male,17.0,0,0,$8.6625,S,NaN
164,0,3,male,1.0,4,1,$39.6875,S,NaN
165,1,3,male,9.0,0,2,$20.525,S,NaN
166,1,1,female,Missing Data,0,1,$55.0,S,E
167,0,3,female,45.0,1,4,$27.9,S,NaN
168,0,1,male,Missing Data,0,0,$25.925,S,NaN
169,0,3,male,28.0,0,0,$56.4958,S,NaN
170,0,1,male,61.0,0,0,$33.5,S,B
171,0,3,male,4.0,4,1,$29.125,Q,NaN
172,1,3,female,1.0,1,1,$11.1333,S,NaN
173,0,3,male,21.0,0,0,$7.925,S,NaN
174,0,1,male,56.0,0,0,$30.6958,C,A
175,0,3,male,18.0,1,1,$7.8542,S,NaN
176,0,3,male,Missing Data,3,1,$25.4667,S,NaN
177,0,1,female,50.0,0,0,$28.7125,C,C
178,0,2,male,30.0,0,0,$13.0,S,NaN
179,0,3,male,36.0,0,0,$0.0,S,NaN
180,0,3,female,Missing Data,8,2,$69.55,S,NaN
181,0,2,male,Missing Data,0,0,$15.05,C,NaN
182,0,3,male,9.0,4,2,$31.3875,S,NaN
183,1,2,male,1.0,2,1,$39.0,S,F
184,1,3,female,4.0,0,2,$22.025,S,NaN
185,0,1,male,Missing Data,0,0,$50.0,S,A
186,1,3,female,Missing Data,1,0,$15.5,Q,NaN
187,1,1,male,45.0,0,0,$26.55,S,NaN
188,0,3,male,40.0,1,1,$15.5,Q,NaN
189,0,3,male,36.0,0,0,$7.8958,S,NaN
190,1,2,female,32.0,0,0,$13.0,S,NaN
191,0,2,male,19.0,0,0,$13.0,S,NaN
192,1,3,female,19.0,1,0,$7.8542,S,NaN
193,1,2,male,3.0,1,1,$26.0,S,F
194,1,1,female,44.0,0,0,$27.7208,C,B
195,1,1,female,58.0,0,0,$146.5208,C,B
196,0,3,male,Missing Data,0,0,$7.75,Q,NaN
197,0,3,male,42.0,0,1,$8.4042,S,NaN
198,1,3,female,Missing Data,0,0,$7.75,Q,NaN
199,0,2,female,24.0,0,0,$13.0,S,NaN
200,0,3,male,28.0,0,0,$9.5,S,NaN
201,0,3,male,NaN,8,2,$69.55,S,NaN
202,0,3,male,34.0,0,0,$6.4958,S,NaN
203,0,3,male,45.5,0,0,$7.225,C,NaN
204,1,3,male,18.0,0,0,$8.05,S,NaN
205,0,3,female,2.0,0,1,$10.4625,S,G
206,0,3,male,32.0,1,0,$15.85,S,NaN
207,1,3,male,26.0,0,0,$18.7875,C,NaN
208,1,3,female,16.0,0,0,$7.75,Q,NaN
209,1,1,male,40.0,0,0,$31.0,C,A
210,0,3,male,24.0,0,0,$7.05,S,NaN
211,1,2,female,35.0,0,0,$21.0,S,NaN
212,0,3,male,22.0,0,0,$7.25,S,NaN
213,0,2,male,30.0,0,0,$13.0,S,NaN
214,0,3,male,NaN,1,0,$7.75,Q,NaN
215,1,1,female,31.0,1,0,$113.275,C,D
216,1,3,female,27.0,0,0,$7.925,S,NaN
217,0,2,male,102,1,0,$27.0,S,NaN
218,1,1,female,32.0,0,0,$76.2917,C,D
219,0,2,male,30.0,0,0,$10.5,S,NaN
220,1,3,male,16.0,0,0,$8.05,S,NaN
221,0,2,male,27.0,0,0,$13.0,S,NaN
222,0,3,male,51.0,0,0,$8.05,S,NaN
223,0,3,male,NaN,0,0,$7.8958,S,NaN
224,1,1,male,38.0,1,0,$90.0,S,C
225,0,3,male,22.0,0,0,$9.35,S,NaN
226,1,2,male,19.0,0,0,$10.5,S,NaN
227,0,3,male,20.5,0,0,$7.25,S,NaN
228,0,2,male,18.0,0,0,$13.0,S,NaN
229,0,3,female,NaN,3,1,$25.4667,S,NaN
230,1,1,female,35.0,1,0,$83.475,S,C
231,0,3,male,29.0,0,0,$7.775,S,NaN
232,0,2,male,59.0,0,0,$13.5,S,NaN
233,1,3,female,5.0,4,2,$31.3875,S,NaN
234,0,2,male,24.0,0,0,$10.5,S,NaN
235,0,3,female,NaN,0,0,$7.55,S,NaN
236,0,2,male,44.0,1,0,$26.0,S,NaN
237,1,2,female,8.0,0,2,$26.25,S,NaN
238,0,2,male,19.0,0,0,$10.5,S,NaN
239,0,2,male,33.0,0,0,$12.275,S,NaN
240,0,3,female,NaN,1,0,$14.4542,C,NaN
241,1,3,female,NaN,1,0,$15.5,Q,NaN
242,0,2,male,29.0,0,0,$10.5,S,NaN
243,0,3,male,22.0,0,0,$7.125,S,NaN
244,0,3,male,30.0,0,0,$7.225,C,NaN
245,0,1,male,44.0,2,0,$90.0,Q,C
246,0,3,female,25.0,0,0,$7.775,S,NaN
247,1,2,female,24.0,0,2,$14.5,S,NaN
248,1,1,male,37.0,1,1,$52.5542,S,D
249,0,2,male,54.0,1,0,$26.0,S,NaN
250,0,3,male,NaN,0,0,$7.25,S,NaN
251,0,3,female,29.0,1,1,$10.4625,S,G
252,0,1,male,62.0,0,0,$26.55,S,C
253,0,3,male,30.0,1,0,$16.1,S,NaN
254,0,3,female,41.0,0,2,$20.2125,S,NaN
255,1,3,female,29.0,0,2,$15.2458,C,NaN
256,1,1,female,NaN,0,0,$79.2,C,NaN
257,1,1,female,30.0,0,0,$86.5,S,B
258,1,1,female,35.0,0,0,$512.3292,C,NaN
259,1,2,female,50.0,0,1,$26.0,S,NaN
260,0,3,male,NaN,0,0,$7.75,Q,NaN
261,1,3,male,3.0,4,2,$31.3875,S,NaN
262,0,1,male,52.0,1,1,$79.65,S,E
263,0,1,male,40.0,0,0,$0.0,S,B
264,0,3,female,NaN,0,0,$7.75,Q,NaN
265,0,2,male,36.0,0,0,$10.5,S,NaN
266,0,3,male,16.0,4,1,$39.6875,S,NaN
267,1,3,male,25.0,1,0,$7.775,S,NaN
268,1,1,female,58.0,0,1,$153.4625,S,C
269,1,1,female,35.0,0,0,$135.6333,S,C
270,0,1,male,NaN,0,0,$31.0,S,NaN
271,1,3,male,25.0,0,0,$0.0,S,NaN
272,1,2,female,41.0,0,1,$19.5,S,NaN
273,0,1,male,37.0,0,1,$29.7,C,C
274,1,3,female,NaN,0,0,$7.75,Q,NaN
275,1,1,female,63.0,1,0,$77.9583,S,D
276,0,3,female,45.0,0,0,$7.75,S,NaN
277,0,2,male,NaN,0,0,$0.0,S,NaN
278,0,3,male,7.0,4,1,$29.125,Q,NaN
279,1,3,female,35.0,1,1,$20.25,S,NaN
280,0,3,male,65.0,0,0,$7.75,Q,NaN
281,0,3,male,28.0,0,0,$7.8542,S,NaN
282,0,3,male,16.0,0,0,$9.5,S,NaN
283,1,3,male,19.0,0,0,$8.05,S,NaN
284,0,1,male,NaN,0,0,$26.0,S,A
285,0,3,male,33.0,0,0,$8.6625,C,NaN
286,1,3,male,30.0,0,0,$9.5,S,NaN
287,0,3,male,22.0,0,0,$7.8958,S,NaN
288,1,2,male,42.0,0,0,$13.0,S,NaN
289,1,3,female,22.0,0,0,$7.75,Q,NaN
290,1,1,female,26.0,0,0,$78.85,S,NaN
291,1,1,female,19.0,1,0,$91.0792,C,B
292,0,2,male,36.0,0,0,$12.875,C,D
293,0,3,female,24.0,0,0,$8.85,S,NaN
294,0,3,male,24.0,0,0,$7.8958,S,NaN
295,0,1,male,NaN,0,0,$27.7208,C,NaN
296,0,3,male,23.5,0,0,$7.2292,C,NaN
297,0,1,female,2.0,1,2,$151.55,S,C
298,1,1,male,NaN,0,0,$30.5,S,C
299,1,1,female,50.0,0,1,$247.5208,C,B
300,1,3,female,NaN,0,0,$7.75,Q,NaN
301,1,3,male,NaN,2,0,$23.25,Q,NaN
302,0,3,male,19.0,0,0,$0.0,S,NaN
303,1,2,female,NaN,0,0,$12.35,Q,E
304,0,3,male,NaN,0,0,$8.05,S,NaN
305,1,1,male,0.92,1,2,$151.55,S,C
306,1,1,female,NaN,0,0,$110.8833,C,NaN
307,1,1,female,17.0,1,0,$108.9,C,C
308,0,2,male,30.0,1,0,$24.0,C,NaN
309,1,1,female,30.0,0,0,$56.9292,C,E
310,1,1,female,24.0,0,0,$83.1583,C,C
311,1,1,female,18.0,2,2,$262.375,C,B
312,0,2,female,26.0,1,1,$26.0,S,NaN
313,0,3,male,28.0,0,0,$7.8958,S,NaN
314,0,2,male,43.0,1,1,$26.25,S,NaN
315,1,3,female,26.0,0,0,$7.8542,S,NaN
316,1,2,female,24.0,1,0,$26.0,S,NaN
317,0,2,male,54.0,0,0,$14.0,S,NaN
318,1,1,female,31.0,0,2,$164.8667,S,C
319,1,1,female,40.0,1,1,$134.5,C,E
320,0,3,male,22.0,0,0,$7.25,S,NaN
321,0,3,male,27.0,0,0,$7.8958,S,NaN
322,1,2,female,30.0,0,0,$12.35,Q,NaN
323,1,2,female,22.0,1,1,$29.0,S,NaN
324,0,3,male,NaN,8,2,$69.55,S,NaN
325,1,1,female,36.0,0,0,$135.6333,C,C
326,0,3,male,61.0,0,0,$6.2375,S,NaN
327,1,2,female,36.0,0,0,$13.0,S,D
328,1,3,female,31.0,1,1,$20.525,S,NaN
329,1,1,female,16.0,0,1,$57.9792,C,B
330,1,3,female,NaN,2,0,$23.25,Q,NaN
331,0,1,male,45.5,0,0,$28.5,S,C
332,0,1,male,38.0,0,1,$153.4625,S,C
333,0,3,male,16.0,2,0,$18.0,S,NaN
334,1,1,female,NaN,1,0,$133.65,S,NaN
335,0,3,male,NaN,0,0,$7.8958,S,NaN
336,0,1,male,29.0,1,0,$66.6,S,C
337,1,1,female,41.0,0,0,$134.5,C,E
338,1,3,male,45.0,0,0,$8.05,S,NaN
339,0,1,male,45.0,0,0,$35.5,S,NaN
340,1,2,male,2.0,1,1,$26.0,S,F
341,1,1,female,24.0,3,2,$263.0,S,C
342,0,2,male,28.0,0,0,$13.0,S,NaN
343,0,2,male,25.0,0,0,$13.0,S,NaN
344,0,2,male,36.0,0,0,$13.0,S,NaN
345,1,2,female,24.0,0,0,$13.0,S,F
346,1,2,female,40.0,0,0,$13.0,S,NaN
347,1,3,female,NaN,1,0,$16.1,S,NaN
348,1,3,male,3.0,1,1,$15.9,S,NaN
349,0,3,male,42.0,0,0,$8.6625,S,NaN
350,0,3,male,23.0,0,0,$9.225,S,NaN
351,0,1,male,NaN,0,0,$35.0,S,C
352,0,3,male,15.0,1,1,$7.2292,C,NaN
353,0,3,male,25.0,1,0,$17.8,S,NaN
354,0,3,male,NaN,0,0,$7.225,C,NaN
355,0,3,male,28.0,0,0,$9.5,S,NaN
356,1,1,female,22.0,0,1,$55.0,S,E
357,0,2,female,38.0,0,0,$13.0,S,NaN
358,1,3,female,NaN,0,0,$7.8792,Q,NaN
359,1,3,female,NaN,0,0,$7.8792,Q,NaN
360,0,3,male,40.0,1,4,$27.9,S,NaN
361,0,2,male,29.0,1,0,$27.7208,C,NaN
362,0,3,female,45.0,0,1,$14.4542,C,NaN
363,0,3,male,35.0,0,0,$7.05,S,NaN
364,0,3,male,NaN,1,0,$15.5,Q,NaN
365,0,3,male,30.0,0,0,$7.25,S,NaN
366,1,1,female,60.0,1,0,$75.25,C,D
367,1,3,female,NaN,0,0,$7.2292,C,NaN
368,1,3,female,NaN,0,0,$7.75,Q,NaN
369,1,1,female,24.0,0,0,$69.3,C,B
370,1,1,male,25.0,1,0,$55.4417,C,E
371,0,3,male,18.0,1,0,$6.4958,S,NaN
372,0,3,male,19.0,0,0,$8.05,S,NaN
373,0,1,male,22.0,0,0,$135.6333,C,NaN
374,0,3,female,3.0,3,1,$21.075,S,NaN
375,1,1,female,NaN,1,0,$82.1708,C,NaN
376,1,3,female,22.0,0,0,$7.25,S,NaN
377,0,1,male,27.0,0,2,$211.5,C,C
378,0,3,male,20.0,0,0,$4.0125,C,NaN
379,0,3,male,19.0,0,0,$7.775,S,NaN
380,1,1,female,42.0,0,0,$227.525,C,NaN
381,1,3,female,1.0,0,2,$15.7417,C,NaN
382,0,3,male,32.0,0,0,$7.925,S,NaN
383,1,1,female,35.0,1,0,$52.0,S,NaN
384,0,3,male,NaN,0,0,$7.8958,S,NaN
385,0,2,male,18.0,0,0,$73.5,S,NaN
386,0,3,male,1.0,5,2,$46.9,S,NaN
387,1,2,female,36.0,0,0,$13.0,S,NaN
388,0,3,male,NaN,0,0,$7.7292,Q,NaN
389,1,2,female,17.0,0,0,$12.0,C,NaN
390,1,1,male,36.0,1,2,$120.0,S,B
391,1,3,male,21.0,0,0,$7.7958,S,NaN
392,0,3,male,28.0,2,0,$7.925,S,NaN
393,1,1,female,23.0,1,0,$113.275,C,D
394,1,3,female,24.0,0,2,$16.7,S,G
395,0,3,male,22.0,0,0,$7.7958,S,NaN
396,0,3,female,31.0,0,0,$7.8542,S,NaN
397,0,2,male,46.0,0,0,$26.0,S,NaN
398,0,2,male,23.0,0,0,$10.5,S,NaN
399,1,2,female,28.0,0,0,$12.65,S,NaN
400,1,3,male,39.0,0,0,$7.925,S,NaN
401,0,3,male,26.0,0,0,$8.05,S,NaN
402,0,3,female,21.0,1,0,$9.825,S,NaN
403,0,3,male,28.0,1,0,$15.85,S,NaN
404,0,3,female,20.0,0,0,$8.6625,S,NaN
405,0,2,male,34.0,1,0,$21.0,S,NaN
406,0,3,male,51.0,0,0,$7.75,S,NaN
407,1,2,male,3.0,1,1,$18.75,S,NaN
408,0,3,male,21.0,0,0,$7.775,S,NaN
409,0,3,female,NaN,3,1,$25.4667,S,NaN
410,0,3,male,NaN,0,0,$7.8958,S,NaN
411,0,3,male,NaN,0,0,$6.8583,Q,NaN
412,1,1,female,33.0,1,0,$90.0,Q,C
413,0,2,male,NaN,0,0,$0.0,S,NaN
414,1,3,male,44.0,0,0,$7.925,S,NaN
415,0,3,female,NaN,0,0,$8.05,S,NaN
416,1,2,female,34.0,1,1,$32.5,S,NaN
417,1,2,female,18.0,0,2,$13.0,S,NaN
418,0,2,male,30.0,0,0,$13.0,S,NaN
419,0,3,female,10.0,0,2,$24.15,S,NaN
420,0,3,male,NaN,0,0,$7.8958,C,NaN
421,0,3,male,21.0,0,0,$7.7333,Q,NaN
422,0,3,male,29.0,0,0,$7.875,S,NaN
423,0,3,female,28.0,1,1,$14.4,S,NaN
424,0,3,male,18.0,1,1,$20.2125,S,NaN
425,0,3,male,NaN,0,0,$7.25,S,NaN
426,1,2,female,28.0,1,0,$26.0,S,NaN
427,1,2,female,19.0,0,0,$26.0,S,NaN
428,0,3,male,NaN,0,0,$7.75,Q,NaN
429,1,3,male,32.0,0,0,$8.05,S,E
430,1,1,male,28.0,0,0,$26.55,S,C
431,1,3,female,NaN,1,0,$16.1,S,NaN
432,1,2,female,42.0,1,0,$26.0,S,NaN
433,0,3,male,17.0,0,0,$7.125,S,NaN
434,0,1,male,50.0,1,0,$55.9,S,E
435,1,1,female,14.0,1,2,$120.0,S,B
436,0,3,female,21.0,2,2,$34.375,S,NaN
437,1,2,female,24.0,2,3,$18.75,S,NaN
438,0,1,male,64.0,1,4,$263.0,S,C
439,0,2,male,31.0,0,0,$10.5,S,NaN
440,1,2,female,45.0,1,1,$26.25,S,NaN
441,0,3,male,20.0,0,0,$9.5,S,NaN
442,0,3,male,25.0,1,0,$7.775,S,NaN
443,1,2,female,28.0,0,0,$13.0,S,NaN
444,1,3,male,NaN,0,0,$8.1125,S,NaN
445,1,1,male,4.0,0,2,$81.8583,S,A
446,1,2,female,13.0,0,1,$19.5,S,NaN
447,1,1,male,34.0,0,0,$26.55,S,NaN
448,1,3,female,5.0,2,1,$19.2583,C,NaN
449,1,1,male,52.0,0,0,$30.5,S,C
450,0,2,male,36.0,1,2,$27.75,S,NaN
451,0,3,male,NaN,1,0,$19.9667,S,NaN
452,0,1,male,30.0,0,0,$27.75,C,C
453,1,1,male,490,1,0,$89.1042,C,C
454,0,3,male,NaN,0,0,$8.05,S,NaN
455,1,3,male,29.0,0,0,$7.8958,C,NaN
456,0,1,male,65.0,0,0,$26.55,S,E
457,1,1,female,NaN,1,0,$51.8625,S,D
458,1,2,female,50.0,0,0,$10.5,S,NaN
459,0,3,male,NaN,0,0,$7.75,Q,NaN
460,1,1,male,48.0,0,0,$26.55,S,E
461,0,3,male,34.0,0,0,$8.05,S,NaN
462,0,1,male,47.0,0,0,$38.5,S,E
463,0,2,male,48.0,0,0,$13.0,S,NaN
464,0,3,male,NaN,0,0,$8.05,S,NaN
465,0,3,male,38.0,0,0,$7.05,S,NaN
466,0,2,male,NaN,0,0,$0.0,S,NaN
467,0,1,male,56.0,0,0,$26.55,S,NaN
468,0,3,male,NaN,0,0,$7.725,Q,NaN
469,1,3,female,0.75,2,1,$19.2583,C,NaN
470,0,3,male,NaN,0,0,$7.25,S,NaN
471,0,3,male,38.0,0,0,$8.6625,S,NaN
472,1,2,female,33.0,1,2,$27.75,S,NaN
473,1,2,female,23.0,0,0,$13.7917,C,D
474,0,3,female,22.0,0,0,$9.8375,S,NaN
475,0,1,male,NaN,0,0,$52.0,S,A
476,0,2,male,34.0,1,0,$21.0,S,NaN
477,0,3,male,29.0,1,0,$7.0458,S,NaN
478,0,3,male,22.0,0,0,$7.5208,S,NaN
479,1,3,female,2.0,0,1,$12.2875,S,NaN
480,0,3,male,9.0,5,2,$46.9,S,NaN
481,0,2,male,NaN,0,0,$0.0,S,NaN
482,0,3,male,50.0,0,0,$8.05,S,NaN
483,1,3,female,63.0,0,0,$9.5875,S,NaN
484,1,1,male,25.0,1,0,$91.0792,C,B
485,0,3,female,NaN,3,1,$25.4667,S,NaN
486,1,1,female,35.0,1,0,$90.0,S,C
487,0,1,male,58.0,0,0,$29.7,C,B
488,0,3,male,30.0,0,0,$8.05,S,NaN
489,1,3,male,9.0,1,1,$15.9,S,NaN
490,0,3,male,NaN,1,0,$19.9667,S,NaN
491,0,3,male,21.0,0,0,$7.25,S,NaN
492,0,1,male,55.0,0,0,$30.5,S,C
493,0,1,male,71.0,0,0,$49.5042,C,NaN
494,0,3,male,21.0,0,0,$8.05,S,NaN
495,0,3,male,NaN,0,0,$14.4583,C,NaN
496,1,1,female,54.0,1,0,$78.2667,C,D
497,0,3,male,NaN,0,0,$15.1,S,NaN
498,0,1,female,25.0,1,2,$151.55,S,C
499,0,3,male,24.0,0,0,$7.7958,S,NaN
500,0,3,male,17.0,0,0,$8.6625,S,NaN
501,0,3,female,21.0,0,0,$7.75,Q,NaN
502,0,3,female,NaN,0,0,$7.6292,Q,NaN
503,0,3,female,37.0,0,0,$9.5875,S,NaN
504,1,1,female,16.0,0,0,$86.5,S,B
505,0,1,male,18.0,1,0,$108.9,C,C
506,1,2,female,33.0,0,2,$26.0,S,NaN
507,1,1,male,NaN,0,0,$26.55,S,NaN
508,0,3,male,28.0,0,0,$22.525,S,NaN
509,1,3,male,26.0,0,0,$56.4958,S,NaN
510,1,3,male,29.0,0,0,$7.75,Q,NaN
511,0,3,male,NaN,0,0,$8.05,S,NaN
512,1,1,male,36.0,0,0,$26.2875,S,E
513,1,1,female,54.0,1,0,$59.4,C,NaN
514,0,3,male,24.0,0,0,$7.4958,S,NaN
515,0,1,male,47.0,0,0,$34.0208,S,D
516,1,2,female,34.0,0,0,$10.5,S,F
517,0,3,male,NaN,0,0,$24.15,Q,NaN
518,1,2,female,36.0,1,0,$26.0,S,NaN
519,0,3,male,32.0,0,0,$7.8958,S,NaN
520,1,1,female,30.0,0,0,$93.5,S,B
521,0,3,male,22.0,0,0,$7.8958,S,NaN
522,0,3,male,NaN,0,0,$7.225,C,NaN
523,1,1,female,44.0,0,1,$57.9792,C,B
524,0,3,male,NaN,0,0,$7.2292,C,NaN
525,0,3,male,40.5,0,0,$7.75,Q,NaN
526,1,2,female,50.0,0,0,$10.5,S,NaN
527,0,1,male,NaN,0,0,$221.7792,S,C
528,0,3,male,39.0,0,0,$7.925,S,NaN
529,0,2,male,23.0,2,1,$11.5,S,NaN
530,1,2,female,2.0,1,1,$26.0,S,NaN
531,0,3,male,NaN,0,0,$7.2292,C,NaN
532,0,3,male,17.0,1,1,$7.2292,C,NaN
533,1,3,female,NaN,0,2,$22.3583,C,NaN
534,0,3,female,30.0,0,0,$8.6625,S,NaN
535,1,2,female,7.0,0,2,$26.25,S,NaN
536,0,1,male,45.0,0,0,$26.55,S,B
537,1,1,female,30.0,0,0,$106.425,C,NaN
538,0,3,male,NaN,0,0,$14.5,S,NaN
539,1,1,female,22.0,0,2,$49.5,C,B
540,1,1,female,36.0,0,2,$71.0,S,B
541,0,3,female,9.0,4,2,$31.275,S,NaN
542,0,3,female,11.0,4,2,$31.275,S,NaN
543,1,2,male,32.0,1,0,$26.0,S,NaN
544,no,1,male,50.0,1,0,$106.425,C,C
545,0,1,male,64.0,0,0,$26.0,S,NaN
546,1,2,female,19.0,1,0,$26.0,S,NaN
547,1,2,male,NaN,0,0,$13.8625,C,NaN
548,0,3,male,33.0,1,1,$20.525,S,NaN
549,1,2,male,8.0,1,1,$36.75,S,NaN
550,1,1,male,17.0,0,2,$110.8833,C,C
551,0,2,male,27.0,0,0,$26.0,S,NaN
552,0,3,male,NaN,0,0,$7.8292,Q,NaN
553,1,3,male,22.0,0,0,$7.225,C,NaN
554,1,3,female,22.0,0,0,$7.775,S,NaN
555,0,1,male,62.0,0,0,$26.55,S,NaN
556,1,1,female,48.0,1,0,$39.6,C,A

In [8]:
col_names=["survived","Class","Gender","Age","SipSp","ParCh","Fare","Emb","Deck"]

In [9]:
titanic= pd.read_csv('titanic_raw.csv',header=None,skiprows=3,skipfooter=2,names= col_names)

<ipython-input-9-d66bc95121f5>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  titanic= pd.read_csv('titanic_raw.csv',header=None,skiprows=3,skipfooter=2,names= col_names)

In [10]:
titanic

    survived  Class  Gender           Age  SipSp  ParCh       Fare  Emb Deck
0          0      3    male          22.0      1      0      $7.25    S  NaN
1          1      1  female          38.0      1      0   $71.2833    C    C
2          1      3  female          26.0      0      0     $7.925    S  NaN
3          1      1  female          35.0      1      0      $53.1    S    C
4          0      3    male          35.0      0      0      $8.05    S  NaN
5          0      3    male  Missing Data      0      0    $8.4583    Q  NaN
6          0      1    male          54.0      0      0   $51.8625    S    E
7          0      3    male           2.0      3      1    $21.075    S  NaN
8          1      3  female          27.0      0      2   $11.1333    S  NaN
9          1      2  female          14.0      1      0   $30.0708    C  NaN
10         1      3  female           4.0      1      1      $16.7    S    G
11         1      1  female          58.0      0      0     $26.55    S    C
12         0      3    male          20.0      0      0      $8.05    S  NaN
13         0      3    male          39.0      1      5    $31.275    S  NaN
14         0      3  female          14.0      0      0    $7.8542    S  NaN
15         1      2  female          55.0      0      0      $16.0    S  NaN
16         0      3    male           2.0      4      1    $29.125    Q  NaN
17         1      2    male  Missing Data      0      0      $13.0    S  NaN
18         0      3  female          31.0      1      0      $18.0    S  NaN
19         1      3  female  Missing Data      0      0     $7.225    C  NaN
20         0      2    male          35.0      0      0      $26.0    S  NaN
21         1      2    male          34.0      0      0      $13.0    S    D
22         1      3  female          15.0      0      0    $8.0292    Q  NaN
23         1      1    male          28.0      0      0      $35.5    S    A
24         0      3  female           8.0      3      1    $21.075    S  NaN
25         1      3  female          38.0      1      5   $31.3875    S  NaN
26         0      3    male  Missing Data      0      0     $7.225    C  NaN
27         0      1    male          19.0      3      2     $263.0    S    C
28         1      3  female  Missing Data      0      0    $7.8792    Q  NaN
29         0      3    male  Missing Data      0      0    $7.8958    S  NaN
30         0      1    male          40.0      0      0   $27.7208    C  NaN
31         1      1  female  Missing Data      1      0  $146.5208    C    B
32         1      3  female  Missing Data      0      0      $7.75    Q  NaN
33         0      2    male          66.0      0      0      $10.5    S  NaN
34         0      1    male          28.0      1      0   $82.1708    C  NaN
35         0      1    male          42.0      1      0      $52.0    S  NaN
36         1      3    male  Missing Data      0      0    $7.2292    C  NaN
37         0      3    male          21.0      0      0      $8.05    S  NaN
38         0      3  female          18.0      2      0      $18.0    S  NaN
39         1      3  female          14.0      1      0   $11.2417    C  NaN
40         0      3  female          40.0      1      0     $9.475    S  NaN
41         0      2  female          27.0      1      0      $21.0    S  NaN
42         0      3    male  Missing Data      0      0    $7.8958    C  NaN
43         1      2  female           3.0      1      2   $41.5792    C  NaN
44         1      3  female          19.0      0      0    $7.8792    Q  NaN
45         0      3    male  Missing Data      0      0      $8.05    S  NaN
46         0      3    male  Missing Data      1      0      $15.5    Q  NaN
47         1      3  female  Missing Data      0      0      $7.75    Q  NaN
48         0      3    male  Missing Data      2      0   $21.6792    C  NaN
49         0      3  female          18.0      1      0      $17.8    S  NaN
50         0      3    male           7.0      4      1   $39.6875    S  NaN
51         0      3    male          21.0      0      0       $7.8    S  NaN
52         1      1  female          49.0      1      0   $76.7292    C    D
53         1      2  female          29.0      1      0      $26.0    S  NaN
54         0      1    male          65.0      0      1   $61.9792    C    B
55         1      1    male  Missing Data      0      0      $35.5    S    C
56         1      2  female          21.0      0      0      $10.5    S  NaN
57         0      3    male          28.5      0      0    $7.2292    C  NaN
58         1      2  female           5.0      1      2     $27.75    S  NaN
59         0      3    male          11.0      5      2      $46.9    S  NaN
60         0      3    male          22.0      0      0    $7.2292    C  NaN
61         1      1  female          38.0      0      0      $80.0  NaN    B
62         0      1    male          45.0      1      0    $83.475    S    C
63         0      3    male           4.0      3      2      $27.9    S  NaN
64         0      1    male  Missing Data      0      0   $27.7208    C  NaN
65         1      3    male  Missing Data      1      1   $15.2458    C  NaN
66         1      2  female          29.0      0      0      $10.5    S    F
67         0      3    male          19.0      0      0    $8.1583    S  NaN
68         1      3  female          17.0      4      2     $7.925    S  NaN
69         0      3    male          26.0      2      0    $8.6625    S  NaN
70         0      2    male          32.0      0      0      $10.5    S  NaN
71         0      3  female          16.0      5      2      $46.9    S  NaN
72         0      2    male          21.0      0      0      $73.5    S  NaN
73         0      3    male          26.0      1      0   $14.4542    C  NaN
74         1      3    male          32.0      0      0   $56.4958    S  NaN
75         0      3    male          25.0      0      0      $7.65    S    F
76         0      3    male  Missing Data      0      0    $7.8958    S  NaN
77         0      3    male  Missing Data      0      0      $8.05    S  NaN
78         1      2    male          0.83      0      2      $29.0    S  NaN
79         1      3  female          30.0      0      0    $12.475    S  NaN
80         0      3    male          22.0      0      0       $9.0    S  NaN
81         1      3    male          29.0      0      0       $9.5    S  NaN
82         1      3  female  Missing Data      0      0    $7.7875    Q  NaN
83         0      1    male          28.0      0      0      $47.1    S  NaN
84         1      2  female          17.0      0      0      $10.5    S  NaN
85         1      3  female          33.0      3      0     $15.85    S  NaN
86         0      3    male          16.0      1      3    $34.375    S  NaN
87         0      3    male  Missing Data      0      0      $8.05    S  NaN
88         1      1  female          23.0      3      2     $263.0    S    C
89         0      3    male          24.0      0      0      $8.05    S  NaN
90         0      3    male          29.0      0      0      $8.05    S  NaN
91         0      3    male          20.0      0      0    $7.8542    S  NaN
92         0      1    male          46.0      1      0    $61.175    S    E
93         0      3    male          26.0      1      2    $20.575    S  NaN
94         0      3    male          59.0      0      0      $7.25    S  NaN
95         0      3    male  Missing Data      0      0      $8.05    S  NaN
96         0      1    male          71.0      0      0   $34.6542    C    A
97         1      1    male          23.0      0      1   $63.3583    C    D
98         1      2  female          34.0      0      1      $23.0    S  NaN
99         0      2    male          34.0      1      0      $26.0    S  NaN
100        0      3  female          28.0      0      0    $7.8958    S  NaN
101        0      3    male  Missing Data      0      0    $7.8958    S  NaN
102        0      1    male          21.0      0      1   $77.2875    S    D
103        0      3    male          33.0      0      0    $8.6542    S  NaN
104        0      3    male          37.0      2      0     $7.925    S  NaN
105        0      3    male          28.0      0      0    $7.8958    S  NaN
106        1      3  female          21.0      0      0      $7.65    S  NaN
107        1      3    male  Missing Data      0      0     $7.775    S  NaN
108        0      3    male          38.0      0      0    $7.8958    S  NaN
109        1      3  female  Missing Data      1      0     $24.15    Q  NaN
110        0      1    male          47.0      0      0      $52.0    S    C
111        0      3  female          14.5      1      0   $14.4542    C  NaN
112        0      3    male          22.0      0      0      $8.05    S  NaN
113        0      3  female          20.0      1      0     $9.825    S  NaN
114        0      3  female          17.0      0      0   $14.4583    C  NaN
115        0      3    male          21.0      0      0     $7.925    S  NaN
116        0      3    male          70.5      0      0      $7.75    Q  NaN
117        0      2    male          29.0      1      0      $21.0    S  NaN
118        0      1    male          24.0      0      1  $247.5208    C    B
119        0      3  female           2.0      4      2    $31.275    S  NaN
120        0      2    male          21.0      2      0      $73.5    S  NaN
121        0      3    male  Missing Data      0      0      $8.05    S  NaN
122        0      2    male          32.5      1      0   $30.0708    C  NaN
123      yes      2  female          32.5      0      0      $13.0    S    E
124        0      1    male          54.0      0      1   $77.2875    S    D
125        1      3    male          12.0      1      0   $11.2417    C  NaN
126        0      3    male  Missing Data      0      0      $7.75    Q  NaN
127        1      3    male          24.0      0      0    $7.1417    S  NaN
128        1      3  female  Missing Data      1      1   $22.3583    C    F
129        0      3    male          45.0      0      0     $6.975    S  NaN
130        0      3    male          33.0      0      0    $7.8958    C  NaN
131        0      3    male          20.0      0      0      $7.05    S  NaN
132        0      3  female          47.0      1      0      $14.5    S  NaN
133        1      2  female          29.0      1      0      $26.0    S  NaN
134        0      2    male          25.0      0      0      $13.0    S  NaN
135        0      2    male          23.0      0      0   $15.0458    C  NaN
136        1      1  female          19.0      0      2   $26.2833    S    D
137        0      1    male          37.0      1      0      $53.1    S    C
138        0      3    male          16.0      0      0    $9.2167    S  NaN
139        0      1    male          24.0      0      0      $79.2    C    B
140        0      3  female  Missing Data      0      2   $15.2458    C  NaN
141        1      3  female          22.0      0      0      $7.75    S  NaN
142        1      3  female          24.0      1      0     $15.85    S  NaN
143        0      3    male          19.0      0      0      $6.75    Q  NaN
144        0      2    male          18.0      0      0      $11.5    S  NaN
145        0      2    male          19.0      1      1     $36.75    S  NaN
146        1      3    male          27.0      0      0    $7.7958    S  NaN
147        0      3  female           9.0      2      2    $34.375    S  NaN
148        0      2    male          36.5      0      2      $26.0    S    F
149        0      2    male          42.0      0      0      $13.0    S  NaN
150        0      2    male          51.0      0      0    $12.525    S  NaN
151        1      1  female          22.0      1      0      $66.6    S    C
152        0      3    male          55.5      0      0      $8.05    S  NaN
153        0      3    male          40.5      0      2      $14.5    S  NaN
154        0      3    male  Missing Data      0      0    $7.3125    S  NaN
155        0      1    male          51.0      0      1   $61.3792    C  NaN
156        1      3  female          16.0      0      0    $7.7333    Q  NaN
157        0      3    male          30.0      0      0      $8.05    S  NaN
158        0      3    male  Missing Data      0      0    $8.6625    S  NaN
159        0      3    male  Missing Data      8      2     $69.55    S  NaN
160        0      3    male          44.0      0      1      $16.1    S  NaN
161        1      2  female          40.0      0      0     $15.75    S  NaN
162        0      3    male          26.0      0      0     $7.775    S  NaN
163        0      3    male          17.0      0      0    $8.6625    S  NaN
164        0      3    male           1.0      4      1   $39.6875    S  NaN
165        1      3    male           9.0      0      2    $20.525    S  NaN
166        1      1  female  Missing Data      0      1      $55.0    S    E
167        0      3  female          45.0      1      4      $27.9    S  NaN
168        0      1    male  Missing Data      0      0    $25.925    S  NaN
169        0      3    male          28.0      0      0   $56.4958    S  NaN
170        0      1    male          61.0      0      0      $33.5    S    B
171        0      3    male           4.0      4      1    $29.125    Q  NaN
172        1      3  female           1.0      1      1   $11.1333    S  NaN
173        0      3    male          21.0      0      0     $7.925    S  NaN
174        0      1    male          56.0      0      0   $30.6958    C    A
175        0      3    male          18.0      1      1    $7.8542    S  NaN
176        0      3    male  Missing Data      3      1   $25.4667    S  NaN
177        0      1  female          50.0      0      0   $28.7125    C    C
178        0      2    male          30.0      0      0      $13.0    S  NaN
179        0      3    male          36.0      0      0       $0.0    S  NaN
180        0      3  female  Missing Data      8      2     $69.55    S  NaN
181        0      2    male  Missing Data      0      0     $15.05    C  NaN
182        0      3    male           9.0      4      2   $31.3875    S  NaN
183        1      2    male           1.0      2      1      $39.0    S    F
184        1      3  female           4.0      0      2    $22.025    S  NaN
185        0      1    male  Missing Data      0      0      $50.0    S    A
186        1      3  female  Missing Data      1      0      $15.5    Q  NaN
187        1      1    male          45.0      0      0     $26.55    S  NaN
188        0      3    male          40.0      1      1      $15.5    Q  NaN
189        0      3    male          36.0      0      0    $7.8958    S  NaN
190        1      2  female          32.0      0      0      $13.0    S  NaN
191        0      2    male          19.0      0      0      $13.0    S  NaN
192        1      3  female          19.0      1      0    $7.8542    S  NaN
193        1      2    male           3.0      1      1      $26.0    S    F
194        1      1  female          44.0      0      0   $27.7208    C    B
195        1      1  female          58.0      0      0  $146.5208    C    B
196        0      3    male  Missing Data      0      0      $7.75    Q  NaN
197        0      3    male          42.0      0      1    $8.4042    S  NaN
198        1      3  female  Missing Data      0      0      $7.75    Q  NaN
199        0      2  female          24.0      0      0      $13.0    S  NaN
200        0      3    male          28.0      0      0       $9.5    S  NaN
201        0      3    male           NaN      8      2     $69.55    S  NaN
202        0      3    male          34.0      0      0    $6.4958    S  NaN
203        0      3    male          45.5      0      0     $7.225    C  NaN
204        1      3    male          18.0      0      0      $8.05    S  NaN
205        0      3  female           2.0      0      1   $10.4625    S    G
206        0      3    male          32.0      1      0     $15.85    S  NaN
207        1      3    male          26.0      0      0   $18.7875    C  NaN
208        1      3  female          16.0      0      0      $7.75    Q  NaN
209        1      1    male          40.0      0      0      $31.0    C    A
210        0      3    male          24.0      0      0      $7.05    S  NaN
211        1      2  female          35.0      0      0      $21.0    S  NaN
212        0      3    male          22.0      0      0      $7.25    S  NaN
213        0      2    male          30.0      0      0      $13.0    S  NaN
214        0      3    male           NaN      1      0      $7.75    Q  NaN
215        1      1  female          31.0      1      0   $113.275    C    D
216        1      3  female          27.0      0      0     $7.925    S  NaN
217        0      2    male           102      1      0      $27.0    S  NaN
218        1      1  female          32.0      0      0   $76.2917    C    D
219        0      2    male          30.0      0      0      $10.5    S  NaN
220        1      3    male          16.0      0      0      $8.05    S  NaN
221        0      2    male          27.0      0      0      $13.0    S  NaN
222        0      3    male          51.0      0      0      $8.05    S  NaN
223        0      3    male           NaN      0      0    $7.8958    S  NaN
224        1      1    male          38.0      1      0      $90.0    S    C
225        0      3    male          22.0      0      0      $9.35    S  NaN
226        1      2    male          19.0      0      0      $10.5    S  NaN
227        0      3    male          20.5      0      0      $7.25    S  NaN
228        0      2    male          18.0      0      0      $13.0    S  NaN
229        0      3  female           NaN      3      1   $25.4667    S  NaN
230        1      1  female          35.0      1      0    $83.475    S    C
231        0      3    male          29.0      0      0     $7.775    S  NaN
232        0      2    male          59.0      0      0      $13.5    S  NaN
233        1      3  female           5.0      4      2   $31.3875    S  NaN
234        0      2    male          24.0      0      0      $10.5    S  NaN
235        0      3  female           NaN      0      0      $7.55    S  NaN
236        0      2    male          44.0      1      0      $26.0    S  NaN
237        1      2  female           8.0      0      2     $26.25    S  NaN
238        0      2    male          19.0      0      0      $10.5    S  NaN
239        0      2    male          33.0      0      0    $12.275    S  NaN
240        0      3  female           NaN      1      0   $14.4542    C  NaN
241        1      3  female           NaN      1      0      $15.5    Q  NaN
242        0      2    male          29.0      0      0      $10.5    S  NaN
243        0      3    male          22.0      0      0     $7.125    S  NaN
244        0      3    male          30.0      0      0     $7.225    C  NaN
245        0      1    male          44.0      2      0      $90.0    Q    C
246        0      3  female          25.0      0      0     $7.775    S  NaN
247        1      2  female          24.0      0      2      $14.5    S  NaN
248        1      1    male          37.0      1      1   $52.5542    S    D
249        0      2    male          54.0      1      0      $26.0    S  NaN
250        0      3    male           NaN      0      0      $7.25    S  NaN
251        0      3  female          29.0      1      1   $10.4625    S    G
252        0      1    male          62.0      0      0     $26.55    S    C
253        0      3    male          30.0      1      0      $16.1    S  NaN
254        0      3  female          41.0      0      2   $20.2125    S  NaN
255        1      3  female          29.0      0      2   $15.2458    C  NaN
256        1      1  female           NaN      0      0      $79.2    C  NaN
257        1      1  female          30.0      0      0      $86.5    S    B

In [11]:
titanic.shape

(894, 9)

In [12]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 894 entries, 0 to 893
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  894 non-null    object
 1   Class     894 non-null    int64
 2   Gender    894 non-null    object
 3   Age       758 non-null    object
 4   SipSp     894 non-null    int64
 5   ParCh     894 non-null    int64
 6   Fare      894 non-null    object
 7   Emb       892 non-null    object
 8   Deck      203 non-null    object
dtypes: int64(3), object(6)
memory usage: 69.8+ KB

In [13]:
titanic.isnull().sum()

survived      0
Class         0
Gender        0
Age         136
SipSp         0
ParCh         0
Fare          0
Emb           2
Deck        691
dtype: int64

In [14]:
titanic.survived.value_counts()

0      551
1      341
yes      1
no       1
Name: survived, dtype: int64

In [15]:
titanic.survived.replace(to_replace=['yes','no'],value=[1,0],inplace =True)

In [16]:
titanic.survived.value_counts()

0    551
1    341
0      1
1      1
Name: survived, dtype: int64

In [17]:
titanic.survived= titanic.survived.astype('int')

In [18]:
titanic.Class.value_counts()

3    493
1    216
2    185
Name: Class, dtype: int64

In [19]:
titanic.Gender.value_counts()

male      580
female    314
Name: Gender, dtype: int64

In [20]:
titanic.Age.value_counts(dropna=False).head()

NaN             136
Missing Data     41
24.0             31
22.0             27
18.0             26
Name: Age, dtype: int64

In [21]:
import numpy as np

In [22]:
titanic.Age.replace(to_replace='Missing Data',value=np.nan,inplace =True)

In [23]:
titanic.Age.value_counts(dropna=False).head()

NaN     177
24.0     31
22.0     27
18.0     26
30.0     25
Name: Age, dtype: int64

In [24]:
titanic.Age=titanic.Age.astype('float')

In [25]:
titanic.Age.mean()

30.718507670850766

In [26]:
mean=round(titanic.Age.mean(),1)

In [27]:
titanic.Age.fillna(mean,inplace=True)

In [28]:
titanic.SipSp.value_counts()

0    610
1    210
2     28
4     18
3     16
8      7
5      5
Name: SipSp, dtype: int64

In [29]:
titanic.ParCh.value_counts()

0    680
1    119
2     80
3      5
5      5
4      4
6      1
Name: ParCh, dtype: int64

In [30]:
titanic.Fare.value_counts().head()

$8.05      43
$13.0      42
$7.8958    39
$7.75      34
$26.0      31
Name: Fare, dtype: int64

In [31]:
titanic.Fare=titanic.Fare.str.replace("$","")

<ipython-input-31-ca2ef5adecb5>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  titanic.Fare=titanic.Fare.str.replace("$","")

In [32]:
titanic.Fare.head(2)

0       7.25
1    71.2833
Name: Fare, dtype: object

In [33]:
titanic.Fare=titanic.Fare.astype('float')

In [34]:
titanic.head(2)

   survived  Class  Gender   Age  SipSp  ParCh     Fare Emb Deck
0         0      3    male  22.0      1      0   7.2500   S  NaN
1         1      1  female  38.0      1      0  71.2833   C    C

In [35]:
titanic.Emb.value_counts()

S    647
C    168
Q     77
Name: Emb, dtype: int64

In [36]:
titanic.Deck.value_counts(dropna=False)

NaN    691
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: Deck, dtype: int64

In [37]:
titanic.dropna(axis=1,thresh=500,inplace=True)

In [38]:
titanic.fillna(method='ffill',inplace=True)

In [39]:
titanic.shape

(894, 8)

In [40]:
titanic[titanic.duplicated(keep='first')]

     survived  Class  Gender    Age  SipSp  ParCh     Fare Emb
47          1      3  female  30.70      0      0   7.7500   Q
76          0      3    male  30.70      0      0   7.8958   S
77          0      3    male  30.70      0      0   8.0500   S
87          0      3    male  30.70      0      0   8.0500   S
95          0      3    male  30.70      0      0   8.0500   S
101         0      3    male  30.70      0      0   7.8958   S
121         0      3    male  30.70      0      0   8.0500   S
133         1      2  female  29.00      1      0  26.0000   S
173         0      3    male  21.00      0      0   7.9250   S
196         0      3    male  30.70      0      0   7.7500   Q
198         1      3  female  30.70      0      0   7.7500   Q
201         0      3    male  30.70      8      2  69.5500   S
213         0      2    male  30.00      0      0  13.0000   S
223         0      3    male  30.70      0      0   7.8958   S
241         1      3  female  30.70      1      0  15.5000   Q
260         0      3    male  30.70      0      0   7.7500   Q
274         1      3  female  30.70      0      0   7.7500   Q
295         0      1    male  30.70      0      0  27.7208   C
300         1      3  female  30.70      0      0   7.7500   Q
304         0      3    male  30.70      0      0   8.0500   S
313         0      3    male  28.00      0      0   7.8958   S
320         0      3    male  22.00      0      0   7.2500   S
324         0      3    male  30.70      8      2  69.5500   S
335         0      3    male  30.70      0      0   7.8958   S
343         0      2    male  25.00      0      0  13.0000   S
354         0      3    male  30.70      0      0   7.2250   C
355         0      3    male  28.00      0      0   9.5000   S
358         1      3  female  30.70      0      0   7.8792   Q
359         1      3  female  30.70      0      0   7.8792   Q
364         0      3    male  30.70      1      0  15.5000   Q
368         1      3  female  30.70      0      0   7.7500   Q
384         0      3    male  30.70      0      0   7.8958   S
387         1      2  female  36.00      0      0  13.0000   S
409         0      3  female  30.70      3      1  25.4667   S
410         0      3    male  30.70      0      0   7.8958   S
413         0      2    male  30.70      0      0   0.0000   S
418         0      2    male  30.00      0      0  13.0000   S
420         0      3    male  30.70      0      0   7.8958   C
425         0      3    male  30.70      0      0   7.2500   S
428         0      3    male  30.70      0      0   7.7500   Q
431         1      3  female  30.70      1      0  16.1000   S
454         0      3    male  30.70      0      0   8.0500   S
459         0      3    male  30.70      0      0   7.7500   Q
464         0      3    male  30.70      0      0   8.0500   S
466         0      2    male  30.70      0      0   0.0000   S
470         0      3    male  30.70      0      0   7.2500   S
476         0      2    male  34.00      1      0  21.0000   S
481         0      2    male  30.70      0      0   0.0000   S
485         0      3  female  30.70      3      1  25.4667   S
488         0      3    male  30.00      0      0   8.0500   S
490         0      3    male  30.70      1      0  19.9667   S
494         0      3    male  21.00      0      0   8.0500   S
500         0      3    male  17.00      0      0   8.6625   S
511         0      3    male  30.70      0      0   8.0500   S
521         0      3    male  22.00      0      0   7.8958   S
522         0      3    male  30.70      0      0   7.2250   C
526         1      2  female  50.00      0      0  10.5000   S
531         0      3    male  30.70      0      0   7.2292   C
555         0      1    male  62.00      0      0  26.5500   S
560         0      3    male  30.70      0      0   7.7500   Q
563         0      3    male  30.70      0      0   8.0500   S
564         0      3  female  30.70      0      0   8.0500   S
568         0      3    male  30.70      0      0   7.2292   C
573         1      3  female  30.70      0      0   7.7500   Q
588         0      3    male  22.00      0      0   8.0500   S
589         0      3    male  30.70      0      0   8.0500   S
598         0      3    male  30.70      0      0   7.2250   C
601         0      3    male  30.70      0      0   7.8958   S
612         1      3  female  30.70      1      0  15.5000   Q
613         0      3    male  30.70      0      0   7.7500   Q
614         0      3    male  35.00      0      0   8.0500   S
635         1      2  female  28.00      0      0  13.0000   S
636         0      3    male  32.00      0      0   7.9250   S
640         0      3    male  20.00      0      0   7.8542   S
641         1      1  female  24.00      0      0  69.3000   C
644         1      3  female   0.75      2      1  19.2583   C
646         0      3    male  19.00      0      0   7.8958   S
650         0      3    male  30.70      0      0   7.8958   S
656         0      3    male  30.70      0      0   7.8958   S
666         0      2    male  25.00      0      0  13.0000   S
674         0      2    male  30.70      0      0   0.0000   S
692         1      3    male  30.70      0      0  56.4958   S
696         0      3    male  44.00      0      0   8.0500   S
709         1      3    male  30.70      1      1  15.2458   C
732         0      2    male  30.70      0      0   0.0000   S
733         0      2    male  23.00      0      0  13.0000   S
734         0      2    male  23.00      0      0  13.0000   S
738         0      3    male  30.70      0      0   7.8958   S
739         0      3    male  30.70      0      0   7.8958   S
757         0      2    male  18.00      0      0  11.5000   S
758         0      3    male  34.00      0      0   8.0500   S
760         0      3    male  30.70      0      0  14.5000   S
773         0      3    male  30.70      0      0   7.2250   C
776         0      3    male  30.70      0      0   7.7500   Q
790         0      3    male  30.70      0      0   7.7500   Q
792         0      3  female  30.70      8      2  69.5500   S
800         0      2    male  34.00      0      0  13.0000   S
808         0      2    male  39.00      0      0  13.0000   S
815         0      1    male  30.70      0      0   0.0000   S
832         0      3    male  30.70      0      0   7.2292   C
837         0      3    male  30.70      0      0   8.0500   S
838         1      3    male  32.00      0      0  56.4958   S
844         0      3    male  17.00      0      0   8.6625   S
846         0      3    male  30.70      8      2  69.5500   S
859         0      3    male  30.70      0      0   7.2292   C
863         0      3  female  30.70      8      2  69.5500   S
870         0      3    male  26.00      0      0   7.8958   S
877         0      3    male  19.00      0      0   7.8958   S
878         0      3    male  30.70      0      0   7.8958   S
884         0      3    male  25.00      0      0   7.0500   S
886         0      2    male  27.00      0      0  13.0000   S
891         0      2    male  24.00      0      0  10.5000   S
892         0      3    male  34.00      1      1  14.4000   S
893         0      3    male  36.00      0      0   7.8958   S

In [41]:
# titanic.drop_duplicates(keep='first',inplace=True)

In [42]:
# titanic.shape

In [43]:
# titanic[titanic.duplicated(keep='first')]

In [44]:
titanic.head(2)

   survived  Class  Gender   Age  SipSp  ParCh     Fare Emb
0         0      3    male  22.0      1      0   7.2500   S
1         1      1  female  38.0      1      0  71.2833   C

In [45]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 894 entries, 0 to 893
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  894 non-null    int32
 1   Class     894 non-null    int64
 2   Gender    894 non-null    object
 3   Age       894 non-null    float64
 4   SipSp     894 non-null    int64
 5   ParCh     894 non-null    int64
 6   Fare      894 non-null    float64
 7   Emb       894 non-null    object
dtypes: float64(2), int32(1), int64(3), object(2)
memory usage: 59.4+ KB

In [46]:
titanic.describe()

         survived       Class         Age       SipSp       ParCh        Fare
count  894.000000  894.000000  894.000000  894.000000  894.000000  894.000000
mean     0.382550    2.309843   30.714843    0.522371    0.381432   32.132824
std      0.486282    0.835370   21.554721    1.101283    0.805171   49.625396
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.903100
50%      0.000000    3.000000   30.700000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000  490.000000    8.000000    6.000000  512.329200

In [47]:
titanic.isnull().sum()

survived    0
Class       0
Gender      0
Age         0
SipSp       0
ParCh       0
Fare        0
Emb         0
dtype: int64

In [48]:
titanic.count()

survived    894
Class       894
Gender      894
Age         894
SipSp       894
ParCh       894
Fare        894
Emb         894
dtype: int64

## Data Analytics

In [49]:
titanic.head(2)

   survived  Class  Gender   Age  SipSp  ParCh     Fare Emb
0         0      3    male  22.0      1      0   7.2500   S
1         1      1  female  38.0      1      0  71.2833   C

In [50]:
titanic['Gender'].value_counts()

male      580
female    314
Name: Gender, dtype: int64

In [51]:
titanic[titanic['Gender']=='male'].shape

(580, 8)

In [52]:
titanic[(titanic['Gender']=='male') & (titanic['Age'] > 70)]

     survived  Class Gender    Age  SipSp  ParCh     Fare Emb
96          0      1   male   71.0      0      0  34.6542   C
116         0      3   male   70.5      0      0   7.7500   Q
217         0      2   male  102.0      1      0  27.0000   S
453         1      1   male  490.0      1      0  89.1042   C
493         0      1   male   71.0      0      0  49.5042   C
630         1      1   male   80.0      0      0  30.0000   S
785         0      3   male  250.0      0      0   7.2500   S
851         0      3   male   74.0      0      0   7.7750   S

In [53]:
titanic['Age'].mean()

30.714843400447425

In [54]:
titanic.iloc[:,3].mean()

30.714843400447425

In [55]:
titanic.iloc[:,3].median()

30.7

In [56]:
titanic.iloc[:,3].mode()

0    30.7
dtype: float64

In [57]:
titanic.iloc[:,3].max()

490.0

In [58]:
titanic.iloc[:,3].min()

0.42

In [59]:
# Age above 80
titanic[titanic.iloc[:,3] >80]

     survived  Class Gender    Age  SipSp  ParCh     Fare Emb
217         0      2   male  102.0      1      0  27.0000   S
453         1      1   male  490.0      1      0  89.1042   C
785         0      3   male  250.0      0      0   7.2500   S

In [60]:
titanic.drop(index=[217,453,785],inplace=True)

In [61]:
titanic.shape

(891, 8)

In [62]:
titanic[(titanic.iloc[:,6] <50) & (titanic.iloc[:,1] == 1)]

     survived  Class  Gender   Age  SipSp  ParCh     Fare Emb
11          1      1  female  58.0      0      0  26.5500   S
23          1      1    male  28.0      0      0  35.5000   S
30          0      1    male  40.0      0      0  27.7208   C
55          1      1    male  30.7      0      0  35.5000   S
64          0      1    male  30.7      0      0  27.7208   C
83          0      1    male  28.0      0      0  47.1000   S
96          0      1    male  71.0      0      0  34.6542   C
136         1      1  female  19.0      0      2  26.2833   S
168         0      1    male  30.7      0      0  25.9250   S
170         0      1    male  61.0      0      0  33.5000   S
174         0      1    male  56.0      0      0  30.6958   C
177         0      1  female  50.0      0      0  28.7125   C
187         1      1    male  45.0      0      0  26.5500   S
194         1      1  female  44.0      0      0  27.7208   C
209         1      1    male  40.0      0      0  31.0000   C
252         0      1    male  62.0      0      0  26.5500   S
263         0      1    male  40.0      0      0   0.0000   S
270         0      1    male  30.7      0      0  31.0000   S
273         0      1    male  37.0      0      1  29.7000   C
284         0      1    male  30.7      0      0  26.0000   S
295         0      1    male  30.7      0      0  27.7208   C
298         1      1    male  30.7      0      0  30.5000   S
331         0      1    male  45.5      0      0  28.5000   S
339         0      1    male  45.0      0      0  35.5000   S
351         0      1    male  30.7      0      0  35.0000   S
430         1      1    male  28.0      0      0  26.5500   S
447         1      1    male  34.0      0      0  26.5500   S
449         1      1    male  52.0      0      0  30.5000   S
452         0      1    male  30.0      0      0  27.7500   C
456         0      1    male  65.0      0      0  26.5500   S
460         1      1    male  48.0      0      0  26.5500   S
462         0      1    male  47.0      0      0  38.5000   S
467         0      1    male  56.0      0      0  26.5500   S
487         0      1    male  58.0      0      0  29.7000   C
492         0      1    male  55.0      0      0  30.5000   S
493         0      1    male  71.0      0      0  49.5042   C
507         1      1    male  30.7      0      0  26.5500   S
512         1      1    male  36.0      0      0  26.2875   S
515         0      1    male  47.0      0      0  34.0208   S
536         0      1    male  45.0      0      0  26.5500   S
539         1      1  female  22.0      0      2  49.5000   C
545         0      1    male  64.0      0      0  26.0000   S
555         0      1    male  62.0      0      0  26.5500   S
556         1      1  female  48.0      1      0  39.6000   C
572         1      1    male  36.0      0      0  26.3875   S
583         0      1    male  36.0      0      0  40.1250   C
602         0      1    male  30.7      0      0  42.4000   S
604         1      1    male  35.0      0      0  26.5500   C
607         1      1    male  27.0      0      0  30.5000   S
625         0      1    male  61.0      0      0  32.3208   S
630         1      1    male  80.0      0      0  30.0000   S
632         1      1    male  32.0      0      0  30.5000   C
633         0      1    male  30.7      0      0   0.0000   S
647         1      1    male  56.0      0      0  35.5000   C
662         0      1    male  47.0      0      0  25.5875   S
694         0      1    male  60.0      0      0  26.5500   S
701         1      1    male  35.0      0      0  26.2875   S
707         1      1    male  42.0      0      0  26.2875   S
710         1      1  female  24.0      0      0  49.5042   C
711         0      1    male  30.7      0      0  26.5500   S
740         1      1    male  30.7      0      0  30.0000   S
766         0      1    male  30.7      0      0  39.6000   C
782         0      1    male  29.0      0      0  30.0000   S
793         0      1    male  30.7      0      0  30.6958   C
796         1      1  female  49.0      0      0  25.9292   S
806         0      1    male  39.0      0      0   0.0000   S
815         0      1    male  30.7      0      0   0.0000   S
822         0      1    male  38.0      0      0   0.0000   S
839         1      1    male  30.7      0      0  29.7000   C
842         1      1  female  30.0      0      0  31.0000   C
853         1      1  female  16.0      0      1  39.4000   S
857         1      1    male  51.0      0      0  26.5500   S
862         1      1  female  48.0      0      0  25.9292   S
872         0      1    male  33.0      0      0   5.0000   S
887         1      1  female  19.0      0      0  30.0000   S
889         1      1    male  26.0      0      0  30.0000   C